class: info.magnolia.analytics.amcharts.data.AmChartDefinition
label: dashboard.chart.pie
chartTypeConfigurationName: single-choice-donat
chartType:
  class: info.magnolia.analytics.amcharts.data.configuration.AmChartType
  type: PieChart
  innerRadius: 50%
  series:
    - name: series
      type: PieSeries
      dataFields:
        - name: category
          value: answer
          jsonPath: $.[*].answer
        - name: value
          value: count
          jsonPath: $.[*].count
      slices:
        strokeWidth: 0
        strokeOpacity: 0.4
        fillModifier:
          type: RadialGradientModifier
          brightnesses: [ -0.8, -0.8, -0.5, 0, -0.5 ]
        strokeModifier:
          type: RadialGradientModifier
          brightnesses: [ -0.8, -0.8, -0.5, 0, -0.5 ]
