// request data matching seed.sql file
// @no-cookie-jar
// @no-log
GET {{host}}{{base_path}}/forms/
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

###

// request data matching seed.sql file
// @no-cookie-jar
// @no-log
GET {{host}}{{base_path}}/forms/2ccd98a1-9081-4beb-a954-c2aa2b3b4248
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

###

// request data matching seed.sql file
// @no-cookie-jar
// @no-log
POST {{host}}{{base_path}}/forms/2ccd98a1-9081-4beb-a954-c2aa2b3b4248
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

[
  {
    "questionId": "c75790a6-6f74-4a1c-8508-5f0bdca4c1dc",
    "value":"powerful"
  },
  {
    "questionId": "837025e9-4002-4943-9d0c-e35c62f92942",
    "value":"life"
  },
  {
    "questionId": "ae27d6ef-d0c9-48b8-bc4f-a621930f36b5",
    "value":"Nikola Tesla"
  },
  {
    "questionId": "d8b56533-2391-423a-950a-a19b40a8b1bc",
    "value":"father"
  },
  {
    "questionId": "d712ca28-b50a-4302-b692-483e67617365",
    "value":"bitcoin"
  },
  {
    "questionId": "dfc8a09b-1112-4f4f-a618-2a9255496d31",
    "value":"night-owl"
  },
  {
    "questionId": "b5ad27d4-9570-4226-aa4f-f7976ed27f3b",
    "value":"flying"
  },
  {
    "questionId": "380e4c1c-6858-4842-b76e-8d7279b6f318",
    "value":"future"
  },
  {
    "questionId": "c23458d4-80bb-4e74-bb05-4dc1c2ccd105",
    "value":"no"
  },
  {
    "questionId": "ea13f315-3988-4511-981f-981aedb0229e",
    "value":"8>"
  },
  {
    "questionId": "00687337-f69a-4b0b-a2b4-60b69eae01cf",
    "value":"WTF"
  },
  {
    "questionId": "e77aed2e-494c-4e6f-8bd6-9a647bbf42e1",
    "value":"individual"
  },
  {
    "questionId": "04fd750f-b958-4f08-bf6b-622b6c87ef52",
    "value":"dev"
  },
  {
    "questionId": "e2440662-89d8-4eaa-adcd-3d65df31b757",
    "value":"pajamas"
  },
  {
    "questionId": "502a3270-3e81-45a2-a4d4-b81571c20150",
    "value":"grandparent"
  }
]

###

// request data matching seed.sql file
// @no-cookie-jar
// @no-log
POST {{host}}{{base_path}}/forms/2ccd98a1-9081-4beb-a954-c2aa2b3b4248
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

[
  {
    "questionId": "c75790a6-6f74-4a1c-8508-5f0bdca4c1dc",
    "value":"clear"
  },
  {
    "questionId": "837025e9-4002-4943-9d0c-e35c62f92942",
    "value":"children"
  },
  {
    "questionId": "ae27d6ef-d0c9-48b8-bc4f-a621930f36b5",
    "value":"Thomas Edison"
  },
  {
    "questionId": "d8b56533-2391-423a-950a-a19b40a8b1bc",
    "value":"father"
  },
  {
    "questionId": "d712ca28-b50a-4302-b692-483e67617365",
    "value":"Autonomous Vehicles"
  },
  {
    "questionId": "dfc8a09b-1112-4f4f-a618-2a9255496d31",
    "value":"early-bird"
  },
  {
    "questionId": "b5ad27d4-9570-4226-aa4f-f7976ed27f3b",
    "value":"invisibility"
  },
  {
    "questionId": "380e4c1c-6858-4842-b76e-8d7279b6f318",
    "value":"present"
  },
  {
    "questionId": "c23458d4-80bb-4e74-bb05-4dc1c2ccd105",
    "value":"wander"
  },
  {
    "questionId": "ea13f315-3988-4511-981f-981aedb0229e",
    "value":"8>"
  },
  {
    "questionId": "00687337-f69a-4b0b-a2b4-60b69eae01cf",
    "value":"SOS"
  },
  {
    "questionId": "e77aed2e-494c-4e6f-8bd6-9a647bbf42e1",
    "value":"individual"
  },
  {
    "questionId": "04fd750f-b958-4f08-bf6b-622b6c87ef52",
    "value":"hr"
  },
  {
    "questionId": "e2440662-89d8-4eaa-adcd-3d65df31b757",
    "value":"other"
  },
  {
    "questionId": "502a3270-3e81-45a2-a4d4-b81571c20150",
    "value":"grandparent"
  },
  {
    "questionId": "502a3270-3e81-45a2-a4d4-b81571c20150",
    "value":"teenager"
  }
]

###

// @no-cookie-jar
// @no-log
POST {{host}}{{base_path}}/forms/a1498658-f379-4dc2-a353-5408da26f789
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

[
  {
    "questionId": "ea13f315-3988-4511-981f-981aedb0123e",
    "value":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero posuere, dictum purus ut, feugiat nibh. Nullam tincidunt arcu ex, ut sagittis mi scelerisque vel. Mauris quis eleifend velit, ac fringilla libero. Mauris facilisis posuere lorem, maximus euismod risus fermentum eget. Donec semper cursus diam vitae accumsan. Nullam elementum leo luctus, mollis ipsum sed, pellentesque dolor. In quis lectus ornare arcu sagittis tempus."
  }
]

###

// request data matching seed.sql file
// @no-cookie-jar
// @no-log
GET {{host}}{{base_path}}/forms/2ccd98a1-9081-4beb-a954-c2aa2b3b4248/results
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

###
